In [1]:
import pandas as pd

comparison = pd.read_csv(
    "../models/model_comparison.csv"
)

comparison

               Model  R2_Score       MAE      RMSE
0  Linear Regression  0.412000  0.172898  0.610759
1      Decision Tree  0.859585  0.015276  0.145850
2      Random Forest  0.907308  0.011902  0.096279
3            XGBoost  0.869432  0.016762  0.135622

# Method 1: Select by Highest R² Score (Most Common)

In [2]:
best_model = comparison.loc[
    comparison["R2_Score"].idxmax()
]

best_model

Model       Random Forest
R2_Score         0.907308
MAE              0.011902
RMSE             0.096279
Name: 2, dtype: object

# Method 2: Select by Lowest Error

In [4]:
best_mae_model = comparison.loc[
    comparison["MAE"].idxmin()
]

best_mae_model

Model       Random Forest
R2_Score         0.907308
MAE              0.011902
RMSE             0.096279
Name: 2, dtype: object

In [3]:
best_rmse_model = comparison.loc[
    comparison["RMSE"].idxmin()
]

best_rmse_model

Model       Random Forest
R2_Score         0.907308
MAE              0.011902
RMSE             0.096279
Name: 2, dtype: object

In [5]:
comparison["Score"] = (
    comparison["R2_Score"]
    - comparison["MAE"]*0.01
    - comparison["RMSE"]*0.01
)

comparison

               Model  R2_Score       MAE      RMSE     Score
0  Linear Regression  0.412000  0.172898  0.610759  0.404163
1      Decision Tree  0.859585  0.015276  0.145850  0.857974
2      Random Forest  0.907308  0.011902  0.096279  0.906227
3            XGBoost  0.869432  0.016762  0.135622  0.867908

In [6]:
best_model = comparison.loc[
    comparison["Score"].idxmax()
]

best_model

Model       Random Forest
R2_Score         0.907308
MAE              0.011902
RMSE             0.096279
Score            0.906227
Name: 2, dtype: object